#CUDA_VISIBLE_DEVICES=7 
python3 train_t2m_trans.py  \
--exp-name rwkv_base_0.5uncond \
--batch-size 128 \
--num-layers 12 \
--embed-dim-gpt 768 \
--nb-code 512 \
--n-head-gpt 16 \
--block-size 51 \
--ff-rate 4 \
--drop-out-rate 0.1 \
--resume-pth pretrained/VQVAE/net_last.pth \
--vq-name VQVAE \
--out-dir output \
--total-iter 300000 \
--lr-scheduler 150000 \
--lr 0.0001 \
--dataname t2m \
--down-t 2 \
--depth 3 \
--quantizer ema_reset \
--eval-iter 1000 \
--pkeep 0.5 \
--dilation-growth-rate 3 \
--vq-act relu